### ISSUE TITLE
How to solve 3d ode equations

### ISSUE THREAD

**Issue by ajogajog** [lululxvi/deeponet#1]
Hi,
First of all, thank you very much for your excellent work.

In case Gravity pendulum, how do I print the predicted value of the variable s2?

I also try to solve a 3D ode equation set, like ds1/dt=g1(x),ds2/dt=g2(x),ds3/dt=g3(x).It works very well, but only outputs the s1 in test ode function.

Looking forward to your reply.

Thank you very much.

**Comment by lululxvi** [comment]
In the case Gravity pendulum, the code only predicts s1. To predict s2, the simplest way is to use two DeepONets, one for s1, and one for s2. The same for 3D case.

**Comment by curiousHG** [comment]
> In the case Gravity pendulum, the code only predicts s1. To predict s2, the simplest way is to use two DeepONets, one for s1, and one for s2. The same for 3D case.
First of all, thank you for your code, sir.
Could you please point out exactly, where should I change the code to train it for the s2.

**Comment by lululxvi** [comment]
Change
https://github.com/lululxvi/deeponet/blob/9f1a07db5ebedf669444c42dbbbfeb64ba6796d2/src/system.py#L98
to
```python
        return sol.y[1, -1:]
```
