### ISSUE TITLE
Number of parameters in `seq2seq` scales with the length**2 of the sequence

### ISSUE THREAD

**Issue by scaomath** [lululxvi/deeponet#10]
https://github.com/lululxvi/deeponet/blob/44e7b5a2356b0e6e00ad101e897342a2f1e87c0b/seq2seq/learner/nn/seq2seq.py#L58-L59

This does not seem right, considering `DeepONet` does not have such kind of dependence.

https://github.com/lululxvi/deeponet/blob/44e7b5a2356b0e6e00ad101e897342a2f1e87c0b/seq2seq/learner/nn/deeponet.py#L39-L41

**Comment by lululxvi** [comment]
You are right. The Seq2Seq model and DeepONet are not exactly used in the same. But the length is fixed in each task.
