### ISSUE TITLE
AttributeError: 'Triple' object has no attribute 'transform_inputs'

### ISSUE THREAD

**Issue by cfd-ai** [lululxvi/deeponet#16]
Any idea how to resolve the following error?
This is for the default  problem = "ode"  test case. 
Backend: tensorflow.compat.v1
TensorFlow version: 2.6.2
Thanks.

Restoring model from model/model.ckpt-37000.ckpt ...

Traceback (most recent call last):
  File "deeponet_pde.py", line 285, in <module>
    main()
  File "deeponet_pde.py", line 281, in main
    run(problem, system, space, T, m, nn, net, lr, epochs, num_train, num_test)
  File "deeponet_pde.py", line 177, in run
    safe_test(model, data, X_test, y_test)
  File "/[HOME-PATH]/tests/deeponet/src/utils.py", line 56, in safe_test
    y_pred.append(model.predict(data.transform_inputs(X_add)))
AttributeError: 'Triple' object has no attribute 'transform_inputs'

**Comment by cfd-ai** [comment]
If I understand correctly, I guess something like this would fix it:

        # Network
        nn = "DeepONet" #OpNN
        if nn == "DeepONet":
            y_pred.append(model.predict(X_add))
        else:
            y_pred.append(model.predict(data.transform_inputs(X_add)))

**Comment by lululxvi** [comment]
See https://github.com/lululxvi/deeponet/issues/14#issuecomment-1025056619
