### ISSUE TITLE
Could a function of Lp space(p=2) be branch input？

### ISSUE THREAD

**Issue by xuliang5115** [lululxvi/deeponet#19]
### Dear Professor.Lulu:
As title.
I notice you employ KL expansion in Learning stochastic operators, and use N eigenfunctions scaled by the eigenvalues as the input of branch net.

> My problem is about Sturm-Liouville problem, the solution is also consist of eigenfunctions and eigenvalues.

Is that mean i should train model for the problem with different number of eigenvalues, and the input of branch net is N orthogonal functions?
If there is no random process, the input of the branch net is function u of variable x, the function is sample from Lp space(p=2) .It's OK use the function u(x) instead of Fourier-Bessel expansion?

**Comment by lululxvi** [comment]
I didn't get your question. Do you solve standard PDE or SPDE?

**Comment by xuliang5115** [comment]
[Problem Description.pptx](https://github.com/lululxvi/deeponet/files/8494700/Problem.Description.pptx)
I try to use a PPT to illustrate my problem, please let me know if the description is unclear or the format is wrong.

**Comment by lululxvi** [comment]
Yes, in your case, you can directly use u as the branch net input.
