### ISSUE TITLE
How DeepONet provides multiple outputs

### ISSUE THREAD

**Issue by xuliang5115** [lululxvi/deeponet#24]
Professor Lu:
For a complex output problem, I divided into two networks with the same structure and hyperparameters for training.
[The previous issue has been resolved](https://github.com/lululxvi/deepxde/discussions/751#discussioncomment-2992256).
So, i need put model1 and model2 in two files.
I use step method to reduce the dimension of Trunk net, the input of each step is the output of the two networks of the previous step. So there is a bug. I think it is necessary to train a network with two outputs at the same time. 
May i ask some relevant examples so i can change my code?

**Comment by lululxvi** [comment]
Please see https://doi.org/10.1016/j.cma.2022.114778 3.1.6. Multiple outputs. There is no example of code online yet. You need to modify the code.
