### ISSUE TITLE
Output as a Mutidimensional array

### ISSUE THREAD

**Issue by luofx23** [lululxvi/deeponet#31]
Dear Prof.Lu, l see that the example codes you put here are codes that deal with scalar outputs, by saying 'scalar' l mean at each position or time  instance where the output function is evaluated, the function is a scalar function. What if my output function is a vector function? Meaning that at each position(or moment), my output is like a two dimensiona vector? 

And l want to know that, if l am going to use the Physics Informed version of DeepONet, like discribed in the Science Advance paper, how am l gonna use deepxde library to achieve that? Looking forward to your reply and thanks!

**Comment by lululxvi** [comment]
For multiple outputs, see https://doi.org/10.1016/j.cma.2022.114778

DeepXDE supports PI-DeepONet, and we will upload some examples later.
