### ISSUE TITLE
About one-standard-deviation

### ISSUE THREAD

**Issue by BraveDrXuTF** [lululxvi/deeponet#36]
Hi, Professor Lu. I want to ask two questions about the error bars and shaded region in the DeepONet paper. 

- Did you use "uncorrected sample standard deviation" (divided by N) or "corrected sample standard deviation" (divided by N-1) to plot shaded region and error bar in the paper? 
- Which software did you use for graphing the error bars and shaded region? 
- Thank you!

**Comment by lululxvi** [comment]
>     * Did you use "uncorrected sample standard deviation" (divided by N) or "corrected sample standard deviation" (divided by N-1) to plot shaded region and error bar in the paper?

I use Python Scipy std function.

>     * Which software did you use for graphing the error bars and shaded region?

Gnuplot.

**Comment by BraveDrXuTF** [comment]
Very helpful, thanks!
