### ISSUE TITLE
About the difference between the term "generalization error" and "test error" in the deeponet paper

### ISSUE THREAD

**Issue by BraveDrXuTF** [lululxvi/deeponet#43]
Dear Dr Lu,
Hello, I want to ask a question about the difference between the term "generalization error" and "test error" in the deeponet paper.
Here, you wrote 'the error of a neural network for previously unseen data', so I understood it as same as 'test error', 
![image](https://github.com/lululxvi/deeponet/assets/47685165/7f470d18-87a2-4de5-aa73-786ad8e68c61)
also, in some of the web results [1](https://stats.stackexchange.com/questions/32756/how-to-compute-the-generalization-error-test-error-in-a-multivariate-regressio) [2](https://www.bing.com/ck/a?!&&p=7a746e4028301084JmltdHM9MTcwMTk5MzYwMCZpZ3VpZD0yNDM2Mzk4My02MGJiLTYwZjItMTMxZC0yODA2NjFmODYxMzImaW5zaWQ9NTQzNA&ptn=3&ver=2&hsh=3&fclid=24363983-60bb-60f2-131d-280661f86132&psq=generalization+error+%3d+test+error%3f&u=a1aHR0cHM6Ly93d3cucmVzZWFyY2hnYXRlLm5ldC9maWd1cmUvVGhlLW1lYW4tZ2VuZXJhbGl6YXRpb24tdGVzdC1lcnJvci12ZXJzdXMtdHJhaW5pbmctZXJyb3Itb2YtYS1saW5lYXItbW9kZWwtZm9yLWEtZ2l2ZW5fZmlnM18xMzA3MjY2NA&ntb=1) seem also approve that: generalization error and test error are the same thing.

However, in fig. 3 abcd you gave subfigures with the test error and generalization error independently, that's why?

![image](https://github.com/lululxvi/deeponet/assets/47685165/58058ec8-b67b-4a5d-8e61-48f4117aaa30)

**Comment by lululxvi** [comment]
Here generalization error = test error - training error.

**Comment by BraveDrXuTF** [comment]
Thanks. I get it now.
