### ISSUE TITLE
How to use the trained model to predict without training?

### ISSUE THREAD

**Issue by blackyichao** [lululxvi/deeponet#6]
Hello Dr. Lu,
Thank you very much for putting forward this DeepONet for our study.I'm very interested in DeepONet .
But now I have a problem.I spent a lot of time generating datasets and training on reaction-diffusion equations. I save the training data set and the best model after training. But how can I use this optimal model to predict the solution of the reaction-diffusion equation without training? How can I modify the code in deeponet_pde.py?
Thank you very much for your time.

**Comment by lululxvi** [comment]
See FAQ on how to save and load trained models.
